# Generated by Django 4.2.10 on 2025-11-04 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('vimeo_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='معرف Vimeo')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط الفيديو')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='ملف الفيديو')),
                ('position', models.CharField(choices=[('hero', 'Hero Section'), ('services', 'Services Section'), ('testimonials', 'Testimonials Section'), ('other', 'Other')], default='hero', max_length=50, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
