# Generated by Django 4.2.4 on 2025-11-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='badge_label',
            field=models.CharField(blank=True, help_text='مثال: وحش الشهر، طبيب ناجح، طالب طموح', max_length=100, null=True, verbose_name='تسمية الشارة'),
        ),
        migrations.AlterField(
            model_name='video',
            name='position',
            field=models.CharField(choices=[('hero', 'Starts Page (Hero Section)'), ('services', 'Services Section'), ('testimonials', 'Testimonials Section'), ('other', 'Other')], default='hero', max_length=50, verbose_name='الموقع'),
        ),
    ]
