"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l#9)xbe0#1xov$yv%^y15^y8#3)suth1#yu6fxllba60339)2!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '*','62.84.179.144', 'info.fxglobals.co']

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://info.fxglobals.co',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8002',
    'http://127.0.0.1:8002',
    'http://localhost:8009',
    'http://127.0.0.1:8009',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'contacts',
    'videos',
    'exams',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'config' / 'templates',  # Config app templates
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite4',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jerusalem'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Where collectstatic collects files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Source static files directory
]
PROJECT_PATH = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_AUTOREFRESH = False  # Disable auto-refresh in production
WHITENOISE_USE_FINDERS = False  # Don't use finders in production (files should be collected)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
    "http://localhost:8009",
    "http://127.0.0.1:8009",
]

CORS_ALLOW_CREDENTIALS = True
# Frontend URL for password reset links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:8009')


LAHZA_SECRET_KEY = os.getenv('LAHZA_SECRET_KEY', 'sk_test_ppMyMbmAtVKU8Z2iuHUsuxG46LV6EdlSC')
LAHZA_PUBLIC_KEY = os.getenv('LAHZA_PUBLIC_KEY', 'pk_test_I4yPfCO5DHBtNApOgmjxobn55fGqFCJhk')
LAHZA_BASE_URL = os.getenv('LAHZA_BASE_URL', 'https://api.lahza.io')
LAHZA_CALLBACK_URL = os.getenv(
    'LAHZA_CALLBACK_URL',
    f"{FRONTEND_URL.rstrip('/')}/payments/lahza-callback"
)

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'info@fxglobals.co')
# IMPORTANT: For Gmail, you MUST use an App Password, not your regular password
# 1. Enable 2-Factor Authentication: https://myaccount.google.com/security
# 2. Generate App Password: https://myaccount.google.com/apppasswords
# 3. Use the 16-character App Password here (or set EMAIL_HOST_PASSWORD environment variable)
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'spjc izvo nggd zfeh')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'info@fxglobals.co')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'info@fxglobals.co')

# reCAPTCHA Enterprise Settings
RECAPTCHA_SITE_KEY = os.getenv('RECAPTCHA_SITE_KEY', '6LfluhcsAAAAAP4Yj4C2orUWz75nFaC5XkDWivPY')
RECAPTCHA_PROJECT_ID = os.getenv('RECAPTCHA_PROJECT_ID', 'fxglobals-40199')  # Google Cloud Project ID
RECAPTCHA_API_KEY = os.getenv('RECAPTCHA_API_KEY', 'AIzaSyCP1-BXCq3TpBC-qH6XPdmwEQIX_vq7djU')  # API Key for reCAPTCHA Enterprise REST API
# Legacy secret key (kept for backward compatibility, but Enterprise uses API_KEY instead)
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')
# Set to False to disable backend reCAPTCHA verification (frontend validation still works)
RECAPTCHA_VERIFY_ENABLED = os.getenv('RECAPTCHA_VERIFY_ENABLED', 'True').lower() == 'true'