# Generated by Django 4.2.10 on 2025-11-04 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='رقم الواتساب')),
                ('goal', models.CharField(blank=True, choices=[('income', 'بدي أخلق دخل إضافي ثابت يحسّن وضعي المادي'), ('career', 'هدفي أخليه شغلي الأساسي وأتفرّغ إله'), ('learn', 'بدي أتعلم المجال وأفهمه بعمق قبل ما أبدأ فعليًا')], max_length=20, null=True, verbose_name='الهدف')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='تم التواصل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تسجيل عميل',
                'verbose_name_plural': 'تسجيلات العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
