# Generated by Django 4.2.4 on 2025-11-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='الرسالة'),
        ),
    ]
