# Generated by Django 4.2.4 on 2025-11-10 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_customercontact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الصفحة')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('short_code', models.CharField(editable=False, max_length=8, unique=True, verbose_name='الكود المختصر')),
                ('description', models.TextField(blank=True, verbose_name='وصف / ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّالة؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'صفحة هبوط',
                'verbose_name_plural': 'صفحات الهبوط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customercontact',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.landingpage', verbose_name='صفحة الهبوط'),
        ),
    ]
