# Generated by Django 4.2.7 on 2025-11-23 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_landingpage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Payment Reference')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('offer_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Offer Type')),
                ('offer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Offer Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('black_friday', 'Black Friday'), ('checkout', 'Checkout'), ('other', 'Other')], default='checkout', max_length=20, verbose_name='Source')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('lahza_response', models.JSONField(blank=True, default=dict, verbose_name='Lahza Response')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='contacts_pa_referen_815e48_idx'), models.Index(fields=['customer_email'], name='contacts_pa_custome_e70976_idx'), models.Index(fields=['status'], name='contacts_pa_status_ea7d12_idx'), models.Index(fields=['created_at'], name='contacts_pa_created_2af1a7_idx')],
            },
        ),
    ]
