# Generated by Django 4.2.7 on 2025-11-23 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackFridaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Settings')),
                ('end_date', models.DateTimeField(verbose_name='Sale End Date/Time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Black Friday Settings',
                'verbose_name_plural': 'Black Friday Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
