# Generated by Django 4.2.7 on 2025-11-24 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_blackfridaysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackfridaysettings',
            name='pre_black_friday_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the pre-Black Friday timer should start counting down', verbose_name='Pre-Black Friday Start Date/Time'),
        ),
    ]
