# Generated by Django 4.2.7 on 2025-11-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_add_pre_black_friday_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
    ]
