# Generated by Django 4.2.7 on 2025-11-24 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_payment_first_name_payment_last_name_payment_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackFridayContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('form_type', models.CharField(choices=[('pre_bf', 'Pre-Black Friday Form'), ('main_contact', 'Main Contact Form'), ('other', 'Other')], default='other', max_length=20, verbose_name='Form Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Black Friday Contact',
                'verbose_name_plural': 'Black Friday Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form_type'], name='contacts_bl_form_ty_7cca07_idx'), models.Index(fields=['created_at'], name='contacts_bl_created_0162d8_idx'), models.Index(fields=['email'], name='contacts_bl_email_0c9def_idx')],
            },
        ),
    ]
