# Generated by Django 4.2.7 on 2025-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_blackfridaycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Brand'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Expiry Month'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Expiry Year'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, help_text='e.g., Visa, Mastercard', max_length=50, null=True, verbose_name='Card Type'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_four_digits',
            field=models.CharField(blank=True, help_text='Last 4 digits of card number', max_length=4, null=True, verbose_name='Last 4 Digits'),
        ),
    ]
