# Generated by Django 4.2.7 on 2025-11-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_payment_card_brand_payment_card_expiry_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackfridaysettings',
            name='show_pay_button',
            field=models.BooleanField(default=True, help_text='When unchecked, the pay button will be hidden and a contact form button will be shown instead', verbose_name='Show Pay Button'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ILS', max_length=3, verbose_name='Currency'),
        ),
    ]
