# Generated by Django 4.2.7 on 2025-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_add_show_pay_button_to_black_friday_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackfridaycontact',
            name='contact_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('trading', 'Trading Consultation'), ('courses', 'Course Information'), ('support', 'Technical Support'), ('payment', 'Payment Issue'), ('other', 'Other')], default='general', help_text='Type of inquiry or request', max_length=20, verbose_name='Contact Type'),
        ),
    ]
