# Generated by Django 4.2.7 on 2025-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_add_contact_type_to_black_friday_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackfridaycontact',
            name='is_contacted',
            field=models.BooleanField(default=False, help_text='Mark as contacted when you have reached out to this contact', verbose_name='Is Contacted'),
        ),
    ]
