# Generated by Django 4.2.7 on 2025-11-26 13:23

from django.db import migrations, models


def migrate_contact_types(apps, schema_editor):
    """Map old contact_type values to new offer-based values"""
    BlackFridayContact = apps.get_model('contacts', 'BlackFridayContact')
    
    # Mapping old values to new values
    # If old value doesn't match, default to 'annual_membership'
    value_mapping = {
        'general': 'annual_membership',
        'trading': 'annual_membership',
        'courses': 'annual_membership',
        'support': 'annual_membership',
        'payment': 'annual_membership',
        'other': 'annual_membership',
    }
    
    for contact in BlackFridayContact.objects.all():
        old_value = contact.contact_type
        new_value = value_mapping.get(old_value, 'annual_membership')
        contact.contact_type = new_value
        contact.save()


def reverse_migrate_contact_types(apps, schema_editor):
    """Reverse migration - map new values back to old values"""
    BlackFridayContact = apps.get_model('contacts', 'BlackFridayContact')
    
    # Map all new values to 'general' as default for reverse
    for contact in BlackFridayContact.objects.all():
        contact.contact_type = 'general'
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_add_is_contacted_to_black_friday_contact'),
    ]

    operations = [
        migrations.RunPython(migrate_contact_types, reverse_migrate_contact_types),
        migrations.AlterField(
            model_name='blackfridaycontact',
            name='contact_type',
            field=models.CharField(choices=[('annual_membership', 'Annual Membership'), ('recommendations_broadcast', 'Recommendations Package + Live Broadcast'), ('live_broadcast', 'Live Broadcast Offer'), ('recommendations', 'Recommendations Offer')], default='annual_membership', help_text='Selected offer type', max_length=30, verbose_name='Contact Type'),
        ),
    ]
