# Generated by Django 4.2.27 on 2026-02-13 14:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_payment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamadanContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الواتساب')),
                ('phase', models.CharField(choices=[('phase1', 'Phase 1'), ('phase2', 'Phase 2')], default='phase1', max_length=10, verbose_name='المرحلة')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='تم التواصل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'تسجيل رمضان',
                'verbose_name_plural': 'تسجيلات رمضان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contacts_ra_email_2c2050_idx'), models.Index(fields=['phone'], name='contacts_ra_phone_ea25a0_idx'), models.Index(fields=['created_at'], name='contacts_ra_created_c0d54d_idx'), models.Index(fields=['phase'], name='contacts_ra_phase_7e7f4c_idx')],
            },
        ),
    ]
