# Generated by Django 4.2.4 on 2025-11-10 10:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الطالب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدخول')),
            ],
            options={
                'verbose_name': 'مشارك في الاختبار',
                'verbose_name_plural': 'المشاركون في الاختبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان السؤال')),
                ('chart_image', models.ImageField(upload_to='exam/charts/', verbose_name='صورة الشارت (مع طمس نصفها)')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='exam/proofs/', verbose_name='صورة التوضيح (للإجابة الصحيحة)')),
                ('correct_answer', models.CharField(choices=[('buy', 'شراء'), ('sell', 'بيع')], max_length=10, verbose_name='الإجابة الصحيحة')),
                ('explanation', models.TextField(blank=True, verbose_name='شرح / ملاحظة إضافية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال في الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال اختبار التداول',
                'verbose_name_plural': 'أسئلة اختبار التداول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('buy', 'شراء'), ('sell', 'بيع')], max_length=10, verbose_name='الإجابة المختارة')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الإجابة')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examparticipant', verbose_name='المشارك')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examquestion', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة الطالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
