# Generated by Django 4.2.4 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipant',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال'),
        ),
    ]
