# Generated by Django 4.2.4 on 2025-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examparticipant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='examparticipant',
            name='last_correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد الإجابات الصحيحة'),
        ),
        migrations.AddField(
            model_name='examparticipant',
            name='last_rating_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملخص التقييم'),
        ),
        migrations.AddField(
            model_name='examparticipant',
            name='last_rating_value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تقييم الاهتمام (1-5)'),
        ),
        migrations.AddField(
            model_name='examparticipant',
            name='last_result_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر نتيجة'),
        ),
        migrations.AddField(
            model_name='examparticipant',
            name='last_score',
            field=models.PositiveIntegerField(default=0, verbose_name='آخر نتيجة (٪)'),
        ),
        migrations.AddField(
            model_name='examparticipant',
            name='last_total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الأسئلة'),
        ),
    ]
